import React, { useState, useEffect } from "react";
import { LuX } from "react-icons/lu";
import EmailEditor from "./EmailEditor";

export default function EmailModal({ 
  open, 
  onClose, 
  vendor, 
  rfqItems = [], 
  rfqData = {}, 
  onSend 
}) {
  // Local state for transitions
  const [visible, setVisible] = useState(open);
  const [isAnimating, setIsAnimating] = useState(false);
  const [sending, setSending] = useState(false);

  // Form fields
  const [emailForm, setEmailForm] = useState({
    to: "",
    subject: "",
    content: ""
  });

  // Handle content change from EmailEditor
  const handleContentChange = (newContent) => {
    setEmailForm(prev => ({
      ...prev,
      content: newContent
    }));
  };

  // Initialize form when modal opens
  useEffect(() => {
    if (open && vendor) {
      const currentDate = new Date().toLocaleDateString();
      
      setEmailForm({
        to: vendor.email || vendor.emailAddress || vendor.EmailAddress || 
            vendor.vendor?.EmailAddress || vendor.details?.EmailAddress || "",
        subject: `Request for Quotation | ${currentDate}`,
        content: "" // Content will be generated by EmailEditor
      });
    }
  }, [open, vendor, rfqItems, rfqData]);

  // Modal transitions
  useEffect(() => {
    if (open) {
      setVisible(true);
      setTimeout(() => setIsAnimating(true), 10);
    } else {
      setIsAnimating(false);
      const timeout = setTimeout(() => setVisible(false), 300);
      return () => clearTimeout(timeout);
    }
  }, [open]);

  if (!open && !visible) return null;

  // Handle form field changes
  const handleFieldChange = (field, value) => {
    setEmailForm(prev => ({
      ...prev,
      [field]: value
    }));
  };

  // Handle send email
  const handleSend = async () => {
    if (!emailForm.to.trim()) {
      alert('Please enter a recipient email address.');
      return;
    }

    setSending(true);
    try {
      await onSend({
        ...emailForm,
        vendor,
        rfqData,
        rfqItems
      });
      onClose();
    } catch (error) {
      console.error('Failed to send email:', error);
      alert('Failed to send email. Please try again.');
    } finally {
      setSending(false);
    }
  };

  // Overlay and modal classes
  const overlayClass = `fixed inset-0 z-40 bg-black bg-opacity-40 transition-opacity duration-300 ease-in-out ${
    isAnimating ? "opacity-50" : "opacity-0"
  }`;

  const modalClass = `fixed left-1/2 top-1/2 z-50 grid w-full max-w-4xl max-h-[90vh] overflow-hidden translate-x-[-50%] translate-y-[-50%] gap-4 border bg-white p-6 shadow-lg transition-all duration-300 ease-in-out ${
    isAnimating
      ? "opacity-100 scale-100"
      : "opacity-0 scale-95 pointer-events-none"
  } sm:rounded-lg`;

  return (
    <>
      {/* Overlay */}
      <div className={overlayClass} aria-hidden="true" onClick={onClose}></div>
      
      {/* Modal */}
      <div
        role="dialog"
        aria-modal="true"
        className={modalClass}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Close button */}
        <button
          type="button"
          className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
          onClick={onClose}
        >
          <LuX className="h-4 w-4" />
          <span className="sr-only">Close</span>
        </button>

        {/* Header */}
        <div className="flex flex-col space-y-1.5 text-center sm:text-left">
          <h2 className="text-lg font-semibold leading-none tracking-tight">
            Send RFQ Email
          </h2>
          <p className="text-sm text-gray-500">
            Send request for quotation to {vendor?.name || 'vendor'}
          </p>
        </div>

        {/* Form */}
        <div className="space-y-4 overflow-y-auto max-h-[60vh]">
          {/* To Field */}
          <div>
            <label className="text-sm font-medium leading-none" htmlFor="to">
              To
            </label>
            <input
              className="flex h-9 w-full rounded-md border border-gray-300 bg-white px-3 py-1 text-sm shadow-sm focus:outline-none focus:ring-1 focus:ring-blue-500"
              id="to"
              type="email"
              placeholder="vendor@example.com"
              value={emailForm.to}
              onChange={(e) => handleFieldChange('to', e.target.value)}
            />
          </div>

          {/* Subject Field */}
          <div>
            <label className="text-sm font-medium leading-none" htmlFor="subject">
              Subject
            </label>
            <input
              className="flex h-9 w-full rounded-md border border-gray-300 bg-white px-3 py-1 text-sm shadow-sm focus:outline-none focus:ring-1 focus:ring-blue-500"
              id="subject"
              placeholder="Email subject"
              value={emailForm.subject}
              onChange={(e) => handleFieldChange('subject', e.target.value)}
            />
          </div>

          {/* Email Content Editor */}
          <div>
            <EmailEditor
              vendor={vendor}
              rfqData={rfqData}
              rfqItems={rfqItems}
              onChange={handleContentChange}
            />
          </div>
        </div>

        {/* Actions */}
        <div className="flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2 mt-4">
          <button
            type="button"
            className="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium border border-gray-300 bg-white shadow-sm hover:bg-gray-100 h-9 px-4 py-2"
            onClick={onClose}
            disabled={sending}
          >
            Cancel
          </button>
          <button
            type="button"
            className="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium bg-blue-600 text-white shadow hover:bg-blue-700 disabled:bg-blue-400 disabled:cursor-not-allowed h-9 px-4 py-2"
            onClick={handleSend}
            disabled={sending}
          >
            {sending ? (
              <div className="flex items-center">
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                Sending...
              </div>
            ) : (
              'Send Email'
            )}
          </button>
        </div>
      </div>
    </>
  );
}